replicaCount: 2         # two pods in prod

appEnv: production

db:
  host: ""              # passed via --set from terraform output
  port: "5432"
  name: "flaskdb"
  user: "postgres"
  password: ""          # passed via --set

ingress:
  enabled: true

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"
