replicaCount: 1         # one pod in staging

appEnv: staging

db:
  host: postgres-headless   # K8s postgres service
  port: "5432"
  name: "studentsdb"
  user: "postgres"
  password: ""              # passed via --set

ingress:
  enabled: false            # no ingress in staging

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "128Mi"
