apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: {{ .Release.Namespace }}
data:
  APP_ENV: {{ .Values.appEnv }}
  DB_HOST: {{ .Values.db.host }}
  DB_PORT: {{ .Values.db.port | quote }}